# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/Documents/GitHub/EmeraldRecomp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Documents/GitHub/EmeraldRecomp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Documents/GitHub/EmeraldRecomp/CMakeFiles /home/alex/Documents/GitHub/EmeraldRecomp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Documents/GitHub/EmeraldRecomp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named verify_rom_hash

# Build rule for target.
verify_rom_hash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 verify_rom_hash
.PHONY : verify_rom_hash

# fast build rule for target.
verify_rom_hash/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_rom_hash.dir/build.make CMakeFiles/verify_rom_hash.dir/build
.PHONY : verify_rom_hash/fast

#=============================================================================
# Target rules for targets named game_launcher_ui

# Build rule for target.
game_launcher_ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_launcher_ui
.PHONY : game_launcher_ui

# fast build rule for target.
game_launcher_ui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/build
.PHONY : game_launcher_ui/fast

#=============================================================================
# Target rules for targets named EmeraldRecomp

# Build rule for target.
EmeraldRecomp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 EmeraldRecomp
.PHONY : EmeraldRecomp

# fast build rule for target.
EmeraldRecomp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/build
.PHONY : EmeraldRecomp/fast

#=============================================================================
# Target rules for targets named gbarecomp_armv4t

# Build rule for target.
gbarecomp_armv4t: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbarecomp_armv4t
.PHONY : gbarecomp_armv4t

# fast build rule for target.
gbarecomp_armv4t/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gbarecomp_armv4t.dir/build.make gbarecomp_build/CMakeFiles/gbarecomp_armv4t.dir/build
.PHONY : gbarecomp_armv4t/fast

#=============================================================================
# Target rules for targets named gbarecomp_recompile_core

# Build rule for target.
gbarecomp_recompile_core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbarecomp_recompile_core
.PHONY : gbarecomp_recompile_core

# fast build rule for target.
gbarecomp_recompile_core/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gbarecomp_recompile_core.dir/build.make gbarecomp_build/CMakeFiles/gbarecomp_recompile_core.dir/build
.PHONY : gbarecomp_recompile_core/fast

#=============================================================================
# Target rules for targets named gbarecomp_gba

# Build rule for target.
gbarecomp_gba: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbarecomp_gba
.PHONY : gbarecomp_gba

# fast build rule for target.
gbarecomp_gba/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gbarecomp_gba.dir/build.make gbarecomp_build/CMakeFiles/gbarecomp_gba.dir/build
.PHONY : gbarecomp_gba/fast

#=============================================================================
# Target rules for targets named gbarecomp_netplay

# Build rule for target.
gbarecomp_netplay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbarecomp_netplay
.PHONY : gbarecomp_netplay

# fast build rule for target.
gbarecomp_netplay/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gbarecomp_netplay.dir/build.make gbarecomp_build/CMakeFiles/gbarecomp_netplay.dir/build
.PHONY : gbarecomp_netplay/fast

#=============================================================================
# Target rules for targets named gbarecomp_heal_gate

# Build rule for target.
gbarecomp_heal_gate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbarecomp_heal_gate
.PHONY : gbarecomp_heal_gate

# fast build rule for target.
gbarecomp_heal_gate/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gbarecomp_heal_gate.dir/build.make gbarecomp_build/CMakeFiles/gbarecomp_heal_gate.dir/build
.PHONY : gbarecomp_heal_gate/fast

#=============================================================================
# Target rules for targets named gbarecomp_runtime

# Build rule for target.
gbarecomp_runtime: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbarecomp_runtime
.PHONY : gbarecomp_runtime

# fast build rule for target.
gbarecomp_runtime/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gbarecomp_runtime.dir/build.make gbarecomp_build/CMakeFiles/gbarecomp_runtime.dir/build
.PHONY : gbarecomp_runtime/fast

#=============================================================================
# Target rules for targets named gbarecomp_debug

# Build rule for target.
gbarecomp_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gbarecomp_debug
.PHONY : gbarecomp_debug

# fast build rule for target.
gbarecomp_debug/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gbarecomp_debug.dir/build.make gbarecomp_build/CMakeFiles/gbarecomp_debug.dir/build
.PHONY : gbarecomp_debug/fast

#=============================================================================
# Target rules for targets named gba_scan

# Build rule for target.
gba_scan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gba_scan
.PHONY : gba_scan

# fast build rule for target.
gba_scan/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gba_scan.dir/build.make gbarecomp_build/CMakeFiles/gba_scan.dir/build
.PHONY : gba_scan/fast

#=============================================================================
# Target rules for targets named gba_recompile

# Build rule for target.
gba_recompile: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gba_recompile
.PHONY : gba_recompile

# fast build rule for target.
gba_recompile/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gba_recompile.dir/build.make gbarecomp_build/CMakeFiles/gba_recompile.dir/build
.PHONY : gba_recompile/fast

#=============================================================================
# Target rules for targets named symbol_import

# Build rule for target.
symbol_import: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 symbol_import
.PHONY : symbol_import

# fast build rule for target.
symbol_import/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/symbol_import.dir/build.make gbarecomp_build/CMakeFiles/symbol_import.dir/build
.PHONY : symbol_import/fast

#=============================================================================
# Target rules for targets named bios_smoke

# Build rule for target.
bios_smoke: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bios_smoke
.PHONY : bios_smoke

# fast build rule for target.
bios_smoke/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/bios_smoke.dir/build.make gbarecomp_build/CMakeFiles/bios_smoke.dir/build
.PHONY : bios_smoke/fast

#=============================================================================
# Target rules for targets named mod_runtime_tests

# Build rule for target.
mod_runtime_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mod_runtime_tests
.PHONY : mod_runtime_tests

# fast build rule for target.
mod_runtime_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/mod_runtime_tests.dir/build.make gbarecomp_build/CMakeFiles/mod_runtime_tests.dir/build
.PHONY : mod_runtime_tests/fast

#=============================================================================
# Target rules for targets named decoder_smoke

# Build rule for target.
decoder_smoke: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 decoder_smoke
.PHONY : decoder_smoke

# fast build rule for target.
decoder_smoke/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/decoder_smoke.dir/build.make gbarecomp_build/CMakeFiles/decoder_smoke.dir/build
.PHONY : decoder_smoke/fast

#=============================================================================
# Target rules for targets named function_finder_tests

# Build rule for target.
function_finder_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 function_finder_tests
.PHONY : function_finder_tests

# fast build rule for target.
function_finder_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/function_finder_tests.dir/build.make gbarecomp_build/CMakeFiles/function_finder_tests.dir/build
.PHONY : function_finder_tests/fast

#=============================================================================
# Target rules for targets named codegen_shards_tests

# Build rule for target.
codegen_shards_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_shards_tests
.PHONY : codegen_shards_tests

# fast build rule for target.
codegen_shards_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/codegen_shards_tests.dir/build.make gbarecomp_build/CMakeFiles/codegen_shards_tests.dir/build
.PHONY : codegen_shards_tests/fast

#=============================================================================
# Target rules for targets named audio_drc_tests

# Build rule for target.
audio_drc_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 audio_drc_tests
.PHONY : audio_drc_tests

# fast build rule for target.
audio_drc_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/audio_drc_tests.dir/build.make gbarecomp_build/CMakeFiles/audio_drc_tests.dir/build
.PHONY : audio_drc_tests/fast

#=============================================================================
# Target rules for targets named selfheal_cluster_test

# Build rule for target.
selfheal_cluster_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 selfheal_cluster_test
.PHONY : selfheal_cluster_test

# fast build rule for target.
selfheal_cluster_test/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/selfheal_cluster_test.dir/build.make gbarecomp_build/CMakeFiles/selfheal_cluster_test.dir/build
.PHONY : selfheal_cluster_test/fast

#=============================================================================
# Target rules for targets named interpreter_smoke

# Build rule for target.
interpreter_smoke: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 interpreter_smoke
.PHONY : interpreter_smoke

# fast build rule for target.
interpreter_smoke/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/interpreter_smoke.dir/build.make gbarecomp_build/CMakeFiles/interpreter_smoke.dir/build
.PHONY : interpreter_smoke/fast

#=============================================================================
# Target rules for targets named armv4t_tests

# Build rule for target.
armv4t_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 armv4t_tests
.PHONY : armv4t_tests

# fast build rule for target.
armv4t_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/armv4t_tests.dir/build.make gbarecomp_build/CMakeFiles/armv4t_tests.dir/build
.PHONY : armv4t_tests/fast

#=============================================================================
# Target rules for targets named thumb_tests

# Build rule for target.
thumb_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 thumb_tests
.PHONY : thumb_tests

# fast build rule for target.
thumb_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/thumb_tests.dir/build.make gbarecomp_build/CMakeFiles/thumb_tests.dir/build
.PHONY : thumb_tests/fast

#=============================================================================
# Target rules for targets named bus_tests

# Build rule for target.
bus_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bus_tests
.PHONY : bus_tests

# fast build rule for target.
bus_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/bus_tests.dir/build.make gbarecomp_build/CMakeFiles/bus_tests.dir/build
.PHONY : bus_tests/fast

#=============================================================================
# Target rules for targets named dma_tests

# Build rule for target.
dma_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dma_tests
.PHONY : dma_tests

# fast build rule for target.
dma_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/dma_tests.dir/build.make gbarecomp_build/CMakeFiles/dma_tests.dir/build
.PHONY : dma_tests/fast

#=============================================================================
# Target rules for targets named timer_tests

# Build rule for target.
timer_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 timer_tests
.PHONY : timer_tests

# fast build rule for target.
timer_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/timer_tests.dir/build.make gbarecomp_build/CMakeFiles/timer_tests.dir/build
.PHONY : timer_tests/fast

#=============================================================================
# Target rules for targets named gpio_tests

# Build rule for target.
gpio_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gpio_tests
.PHONY : gpio_tests

# fast build rule for target.
gpio_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gpio_tests.dir/build.make gbarecomp_build/CMakeFiles/gpio_tests.dir/build
.PHONY : gpio_tests/fast

#=============================================================================
# Target rules for targets named link_tests

# Build rule for target.
link_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 link_tests
.PHONY : link_tests

# fast build rule for target.
link_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/link_tests.dir/build.make gbarecomp_build/CMakeFiles/link_tests.dir/build
.PHONY : link_tests/fast

#=============================================================================
# Target rules for targets named netplay_smoke_tests

# Build rule for target.
netplay_smoke_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 netplay_smoke_tests
.PHONY : netplay_smoke_tests

# fast build rule for target.
netplay_smoke_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/netplay_smoke_tests.dir/build.make gbarecomp_build/CMakeFiles/netplay_smoke_tests.dir/build
.PHONY : netplay_smoke_tests/fast

#=============================================================================
# Target rules for targets named rtc_tests

# Build rule for target.
rtc_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rtc_tests
.PHONY : rtc_tests

# fast build rule for target.
rtc_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/rtc_tests.dir/build.make gbarecomp_build/CMakeFiles/rtc_tests.dir/build
.PHONY : rtc_tests/fast

#=============================================================================
# Target rules for targets named irq_tests

# Build rule for target.
irq_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 irq_tests
.PHONY : irq_tests

# fast build rule for target.
irq_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/irq_tests.dir/build.make gbarecomp_build/CMakeFiles/irq_tests.dir/build
.PHONY : irq_tests/fast

#=============================================================================
# Target rules for targets named ppu_smoke_tests

# Build rule for target.
ppu_smoke_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ppu_smoke_tests
.PHONY : ppu_smoke_tests

# fast build rule for target.
ppu_smoke_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/ppu_smoke_tests.dir/build.make gbarecomp_build/CMakeFiles/ppu_smoke_tests.dir/build
.PHONY : ppu_smoke_tests/fast

#=============================================================================
# Target rules for targets named save_config_tests

# Build rule for target.
save_config_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 save_config_tests
.PHONY : save_config_tests

# fast build rule for target.
save_config_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/save_config_tests.dir/build.make gbarecomp_build/CMakeFiles/save_config_tests.dir/build
.PHONY : save_config_tests/fast

#=============================================================================
# Target rules for targets named presentation_layout_tests

# Build rule for target.
presentation_layout_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 presentation_layout_tests
.PHONY : presentation_layout_tests

# fast build rule for target.
presentation_layout_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/presentation_layout_tests.dir/build.make gbarecomp_build/CMakeFiles/presentation_layout_tests.dir/build
.PHONY : presentation_layout_tests/fast

#=============================================================================
# Target rules for targets named heal_gate_tests

# Build rule for target.
heal_gate_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 heal_gate_tests
.PHONY : heal_gate_tests

# fast build rule for target.
heal_gate_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/heal_gate_tests.dir/build.make gbarecomp_build/CMakeFiles/heal_gate_tests.dir/build
.PHONY : heal_gate_tests/fast

#=============================================================================
# Target rules for targets named gen_codegen_tests

# Build rule for target.
gen_codegen_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gen_codegen_tests
.PHONY : gen_codegen_tests

# fast build rule for target.
gen_codegen_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/gen_codegen_tests.dir/build.make gbarecomp_build/CMakeFiles/gen_codegen_tests.dir/build
.PHONY : gen_codegen_tests/fast

#=============================================================================
# Target rules for targets named codegen_tests

# Build rule for target.
codegen_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen_tests
.PHONY : codegen_tests

# fast build rule for target.
codegen_tests/fast:
	$(MAKE) $(MAKESILENT) -f gbarecomp_build/CMakeFiles/codegen_tests.dir/build.make gbarecomp_build/CMakeFiles/codegen_tests.dir/build
.PHONY : codegen_tests/fast

#=============================================================================
# Target rules for targets named recomp_net

# Build rule for target.
recomp_net: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 recomp_net
.PHONY : recomp_net

# fast build rule for target.
recomp_net/fast:
	$(MAKE) $(MAKESILENT) -f recomp-net-build/CMakeFiles/recomp_net.dir/build.make recomp-net-build/CMakeFiles/recomp_net.dir/build
.PHONY : recomp_net/fast

gbarecomp/host/gbarecomp_codegen_host.o: gbarecomp/host/gbarecomp_codegen_host.c.o
.PHONY : gbarecomp/host/gbarecomp_codegen_host.o

# target to build an object file
gbarecomp/host/gbarecomp_codegen_host.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/gbarecomp/host/gbarecomp_codegen_host.c.o
.PHONY : gbarecomp/host/gbarecomp_codegen_host.c.o

gbarecomp/host/gbarecomp_codegen_host.i: gbarecomp/host/gbarecomp_codegen_host.c.i
.PHONY : gbarecomp/host/gbarecomp_codegen_host.i

# target to preprocess a source file
gbarecomp/host/gbarecomp_codegen_host.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/gbarecomp/host/gbarecomp_codegen_host.c.i
.PHONY : gbarecomp/host/gbarecomp_codegen_host.c.i

gbarecomp/host/gbarecomp_codegen_host.s: gbarecomp/host/gbarecomp_codegen_host.c.s
.PHONY : gbarecomp/host/gbarecomp_codegen_host.s

# target to generate assembly for a file
gbarecomp/host/gbarecomp_codegen_host.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/gbarecomp/host/gbarecomp_codegen_host.c.s
.PHONY : gbarecomp/host/gbarecomp_codegen_host.c.s

recomp-ui/src/common/backends/imgui/launcher_imgui.o: recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.o
.PHONY : recomp-ui/src/common/backends/imgui/launcher_imgui.o

# target to build an object file
recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.o
.PHONY : recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.o

recomp-ui/src/common/backends/imgui/launcher_imgui.i: recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.i
.PHONY : recomp-ui/src/common/backends/imgui/launcher_imgui.i

# target to preprocess a source file
recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.i
.PHONY : recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.i

recomp-ui/src/common/backends/imgui/launcher_imgui.s: recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.s
.PHONY : recomp-ui/src/common/backends/imgui/launcher_imgui.s

# target to generate assembly for a file
recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.s
.PHONY : recomp-ui/src/common/backends/imgui/launcher_imgui.cpp.s

recomp-ui/src/common/backends/imgui/runtime_ui_imgui.o: recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.o
.PHONY : recomp-ui/src/common/backends/imgui/runtime_ui_imgui.o

# target to build an object file
recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.o
.PHONY : recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.o

recomp-ui/src/common/backends/imgui/runtime_ui_imgui.i: recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.i
.PHONY : recomp-ui/src/common/backends/imgui/runtime_ui_imgui.i

# target to preprocess a source file
recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.i
.PHONY : recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.i

recomp-ui/src/common/backends/imgui/runtime_ui_imgui.s: recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.s
.PHONY : recomp-ui/src/common/backends/imgui/runtime_ui_imgui.s

# target to generate assembly for a file
recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.s
.PHONY : recomp-ui/src/common/backends/imgui/runtime_ui_imgui.cpp.s

recomp-ui/src/common/crc32.o: recomp-ui/src/common/crc32.c.o
.PHONY : recomp-ui/src/common/crc32.o

# target to build an object file
recomp-ui/src/common/crc32.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/crc32.c.o
.PHONY : recomp-ui/src/common/crc32.c.o

recomp-ui/src/common/crc32.i: recomp-ui/src/common/crc32.c.i
.PHONY : recomp-ui/src/common/crc32.i

# target to preprocess a source file
recomp-ui/src/common/crc32.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/crc32.c.i
.PHONY : recomp-ui/src/common/crc32.c.i

recomp-ui/src/common/crc32.s: recomp-ui/src/common/crc32.c.s
.PHONY : recomp-ui/src/common/crc32.s

# target to generate assembly for a file
recomp-ui/src/common/crc32.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/crc32.c.s
.PHONY : recomp-ui/src/common/crc32.c.s

recomp-ui/src/common/ips_patch.o: recomp-ui/src/common/ips_patch.c.o
.PHONY : recomp-ui/src/common/ips_patch.o

# target to build an object file
recomp-ui/src/common/ips_patch.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/ips_patch.c.o
.PHONY : recomp-ui/src/common/ips_patch.c.o

recomp-ui/src/common/ips_patch.i: recomp-ui/src/common/ips_patch.c.i
.PHONY : recomp-ui/src/common/ips_patch.i

# target to preprocess a source file
recomp-ui/src/common/ips_patch.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/ips_patch.c.i
.PHONY : recomp-ui/src/common/ips_patch.c.i

recomp-ui/src/common/ips_patch.s: recomp-ui/src/common/ips_patch.c.s
.PHONY : recomp-ui/src/common/ips_patch.s

# target to generate assembly for a file
recomp-ui/src/common/ips_patch.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/ips_patch.c.s
.PHONY : recomp-ui/src/common/ips_patch.c.s

recomp-ui/src/common/keybinds.o: recomp-ui/src/common/keybinds.c.o
.PHONY : recomp-ui/src/common/keybinds.o

# target to build an object file
recomp-ui/src/common/keybinds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/keybinds.c.o
.PHONY : recomp-ui/src/common/keybinds.c.o

recomp-ui/src/common/keybinds.i: recomp-ui/src/common/keybinds.c.i
.PHONY : recomp-ui/src/common/keybinds.i

# target to preprocess a source file
recomp-ui/src/common/keybinds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/keybinds.c.i
.PHONY : recomp-ui/src/common/keybinds.c.i

recomp-ui/src/common/keybinds.s: recomp-ui/src/common/keybinds.c.s
.PHONY : recomp-ui/src/common/keybinds.s

# target to generate assembly for a file
recomp-ui/src/common/keybinds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/keybinds.c.s
.PHONY : recomp-ui/src/common/keybinds.c.s

recomp-ui/src/common/launcher_binds.o: recomp-ui/src/common/launcher_binds.c.o
.PHONY : recomp-ui/src/common/launcher_binds.o

# target to build an object file
recomp-ui/src/common/launcher_binds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_binds.c.o
.PHONY : recomp-ui/src/common/launcher_binds.c.o

recomp-ui/src/common/launcher_binds.i: recomp-ui/src/common/launcher_binds.c.i
.PHONY : recomp-ui/src/common/launcher_binds.i

# target to preprocess a source file
recomp-ui/src/common/launcher_binds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_binds.c.i
.PHONY : recomp-ui/src/common/launcher_binds.c.i

recomp-ui/src/common/launcher_binds.s: recomp-ui/src/common/launcher_binds.c.s
.PHONY : recomp-ui/src/common/launcher_binds.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_binds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_binds.c.s
.PHONY : recomp-ui/src/common/launcher_binds.c.s

recomp-ui/src/common/launcher_boot_timing.o: recomp-ui/src/common/launcher_boot_timing.c.o
.PHONY : recomp-ui/src/common/launcher_boot_timing.o

# target to build an object file
recomp-ui/src/common/launcher_boot_timing.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_boot_timing.c.o
.PHONY : recomp-ui/src/common/launcher_boot_timing.c.o

recomp-ui/src/common/launcher_boot_timing.i: recomp-ui/src/common/launcher_boot_timing.c.i
.PHONY : recomp-ui/src/common/launcher_boot_timing.i

# target to preprocess a source file
recomp-ui/src/common/launcher_boot_timing.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_boot_timing.c.i
.PHONY : recomp-ui/src/common/launcher_boot_timing.c.i

recomp-ui/src/common/launcher_boot_timing.s: recomp-ui/src/common/launcher_boot_timing.c.s
.PHONY : recomp-ui/src/common/launcher_boot_timing.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_boot_timing.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_boot_timing.c.s
.PHONY : recomp-ui/src/common/launcher_boot_timing.c.s

recomp-ui/src/common/launcher_debug.o: recomp-ui/src/common/launcher_debug.c.o
.PHONY : recomp-ui/src/common/launcher_debug.o

# target to build an object file
recomp-ui/src/common/launcher_debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_debug.c.o
.PHONY : recomp-ui/src/common/launcher_debug.c.o

recomp-ui/src/common/launcher_debug.i: recomp-ui/src/common/launcher_debug.c.i
.PHONY : recomp-ui/src/common/launcher_debug.i

# target to preprocess a source file
recomp-ui/src/common/launcher_debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_debug.c.i
.PHONY : recomp-ui/src/common/launcher_debug.c.i

recomp-ui/src/common/launcher_debug.s: recomp-ui/src/common/launcher_debug.c.s
.PHONY : recomp-ui/src/common/launcher_debug.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_debug.c.s
.PHONY : recomp-ui/src/common/launcher_debug.c.s

recomp-ui/src/common/launcher_files.o: recomp-ui/src/common/launcher_files.c.o
.PHONY : recomp-ui/src/common/launcher_files.o

# target to build an object file
recomp-ui/src/common/launcher_files.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_files.c.o
.PHONY : recomp-ui/src/common/launcher_files.c.o

recomp-ui/src/common/launcher_files.i: recomp-ui/src/common/launcher_files.c.i
.PHONY : recomp-ui/src/common/launcher_files.i

# target to preprocess a source file
recomp-ui/src/common/launcher_files.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_files.c.i
.PHONY : recomp-ui/src/common/launcher_files.c.i

recomp-ui/src/common/launcher_files.s: recomp-ui/src/common/launcher_files.c.s
.PHONY : recomp-ui/src/common/launcher_files.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_files.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_files.c.s
.PHONY : recomp-ui/src/common/launcher_files.c.s

recomp-ui/src/common/launcher_gl.o: recomp-ui/src/common/launcher_gl.c.o
.PHONY : recomp-ui/src/common/launcher_gl.o

# target to build an object file
recomp-ui/src/common/launcher_gl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_gl.c.o
.PHONY : recomp-ui/src/common/launcher_gl.c.o

recomp-ui/src/common/launcher_gl.i: recomp-ui/src/common/launcher_gl.c.i
.PHONY : recomp-ui/src/common/launcher_gl.i

# target to preprocess a source file
recomp-ui/src/common/launcher_gl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_gl.c.i
.PHONY : recomp-ui/src/common/launcher_gl.c.i

recomp-ui/src/common/launcher_gl.s: recomp-ui/src/common/launcher_gl.c.s
.PHONY : recomp-ui/src/common/launcher_gl.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_gl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_gl.c.s
.PHONY : recomp-ui/src/common/launcher_gl.c.s

recomp-ui/src/common/launcher_input.o: recomp-ui/src/common/launcher_input.c.o
.PHONY : recomp-ui/src/common/launcher_input.o

# target to build an object file
recomp-ui/src/common/launcher_input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_input.c.o
.PHONY : recomp-ui/src/common/launcher_input.c.o

recomp-ui/src/common/launcher_input.i: recomp-ui/src/common/launcher_input.c.i
.PHONY : recomp-ui/src/common/launcher_input.i

# target to preprocess a source file
recomp-ui/src/common/launcher_input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_input.c.i
.PHONY : recomp-ui/src/common/launcher_input.c.i

recomp-ui/src/common/launcher_input.s: recomp-ui/src/common/launcher_input.c.s
.PHONY : recomp-ui/src/common/launcher_input.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_input.c.s
.PHONY : recomp-ui/src/common/launcher_input.c.s

recomp-ui/src/common/launcher_model.o: recomp-ui/src/common/launcher_model.c.o
.PHONY : recomp-ui/src/common/launcher_model.o

# target to build an object file
recomp-ui/src/common/launcher_model.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_model.c.o
.PHONY : recomp-ui/src/common/launcher_model.c.o

recomp-ui/src/common/launcher_model.i: recomp-ui/src/common/launcher_model.c.i
.PHONY : recomp-ui/src/common/launcher_model.i

# target to preprocess a source file
recomp-ui/src/common/launcher_model.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_model.c.i
.PHONY : recomp-ui/src/common/launcher_model.c.i

recomp-ui/src/common/launcher_model.s: recomp-ui/src/common/launcher_model.c.s
.PHONY : recomp-ui/src/common/launcher_model.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_model.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_model.c.s
.PHONY : recomp-ui/src/common/launcher_model.c.s

recomp-ui/src/common/launcher_ng_capi.o: recomp-ui/src/common/launcher_ng_capi.c.o
.PHONY : recomp-ui/src/common/launcher_ng_capi.o

# target to build an object file
recomp-ui/src/common/launcher_ng_capi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_ng_capi.c.o
.PHONY : recomp-ui/src/common/launcher_ng_capi.c.o

recomp-ui/src/common/launcher_ng_capi.i: recomp-ui/src/common/launcher_ng_capi.c.i
.PHONY : recomp-ui/src/common/launcher_ng_capi.i

# target to preprocess a source file
recomp-ui/src/common/launcher_ng_capi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_ng_capi.c.i
.PHONY : recomp-ui/src/common/launcher_ng_capi.c.i

recomp-ui/src/common/launcher_ng_capi.s: recomp-ui/src/common/launcher_ng_capi.c.s
.PHONY : recomp-ui/src/common/launcher_ng_capi.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_ng_capi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_ng_capi.c.s
.PHONY : recomp-ui/src/common/launcher_ng_capi.c.s

recomp-ui/src/common/launcher_platform_sdl2.o: recomp-ui/src/common/launcher_platform_sdl2.c.o
.PHONY : recomp-ui/src/common/launcher_platform_sdl2.o

# target to build an object file
recomp-ui/src/common/launcher_platform_sdl2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_platform_sdl2.c.o
.PHONY : recomp-ui/src/common/launcher_platform_sdl2.c.o

recomp-ui/src/common/launcher_platform_sdl2.i: recomp-ui/src/common/launcher_platform_sdl2.c.i
.PHONY : recomp-ui/src/common/launcher_platform_sdl2.i

# target to preprocess a source file
recomp-ui/src/common/launcher_platform_sdl2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_platform_sdl2.c.i
.PHONY : recomp-ui/src/common/launcher_platform_sdl2.c.i

recomp-ui/src/common/launcher_platform_sdl2.s: recomp-ui/src/common/launcher_platform_sdl2.c.s
.PHONY : recomp-ui/src/common/launcher_platform_sdl2.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_platform_sdl2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_platform_sdl2.c.s
.PHONY : recomp-ui/src/common/launcher_platform_sdl2.c.s

recomp-ui/src/common/launcher_udp_port.o: recomp-ui/src/common/launcher_udp_port.c.o
.PHONY : recomp-ui/src/common/launcher_udp_port.o

# target to build an object file
recomp-ui/src/common/launcher_udp_port.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_udp_port.c.o
.PHONY : recomp-ui/src/common/launcher_udp_port.c.o

recomp-ui/src/common/launcher_udp_port.i: recomp-ui/src/common/launcher_udp_port.c.i
.PHONY : recomp-ui/src/common/launcher_udp_port.i

# target to preprocess a source file
recomp-ui/src/common/launcher_udp_port.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_udp_port.c.i
.PHONY : recomp-ui/src/common/launcher_udp_port.c.i

recomp-ui/src/common/launcher_udp_port.s: recomp-ui/src/common/launcher_udp_port.c.s
.PHONY : recomp-ui/src/common/launcher_udp_port.s

# target to generate assembly for a file
recomp-ui/src/common/launcher_udp_port.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/launcher_udp_port.c.s
.PHONY : recomp-ui/src/common/launcher_udp_port.c.s

recomp-ui/src/common/recomp_runtime_settings.o: recomp-ui/src/common/recomp_runtime_settings.c.o
.PHONY : recomp-ui/src/common/recomp_runtime_settings.o

# target to build an object file
recomp-ui/src/common/recomp_runtime_settings.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/recomp_runtime_settings.c.o
.PHONY : recomp-ui/src/common/recomp_runtime_settings.c.o

recomp-ui/src/common/recomp_runtime_settings.i: recomp-ui/src/common/recomp_runtime_settings.c.i
.PHONY : recomp-ui/src/common/recomp_runtime_settings.i

# target to preprocess a source file
recomp-ui/src/common/recomp_runtime_settings.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/recomp_runtime_settings.c.i
.PHONY : recomp-ui/src/common/recomp_runtime_settings.c.i

recomp-ui/src/common/recomp_runtime_settings.s: recomp-ui/src/common/recomp_runtime_settings.c.s
.PHONY : recomp-ui/src/common/recomp_runtime_settings.s

# target to generate assembly for a file
recomp-ui/src/common/recomp_runtime_settings.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/recomp_runtime_settings.c.s
.PHONY : recomp-ui/src/common/recomp_runtime_settings.c.s

recomp-ui/src/common/recomp_runtime_ui.o: recomp-ui/src/common/recomp_runtime_ui.c.o
.PHONY : recomp-ui/src/common/recomp_runtime_ui.o

# target to build an object file
recomp-ui/src/common/recomp_runtime_ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/recomp_runtime_ui.c.o
.PHONY : recomp-ui/src/common/recomp_runtime_ui.c.o

recomp-ui/src/common/recomp_runtime_ui.i: recomp-ui/src/common/recomp_runtime_ui.c.i
.PHONY : recomp-ui/src/common/recomp_runtime_ui.i

# target to preprocess a source file
recomp-ui/src/common/recomp_runtime_ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/recomp_runtime_ui.c.i
.PHONY : recomp-ui/src/common/recomp_runtime_ui.c.i

recomp-ui/src/common/recomp_runtime_ui.s: recomp-ui/src/common/recomp_runtime_ui.c.s
.PHONY : recomp-ui/src/common/recomp_runtime_ui.s

# target to generate assembly for a file
recomp-ui/src/common/recomp_runtime_ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/recomp_runtime_ui.c.s
.PHONY : recomp-ui/src/common/recomp_runtime_ui.c.s

recomp-ui/src/common/sha1.o: recomp-ui/src/common/sha1.c.o
.PHONY : recomp-ui/src/common/sha1.o

# target to build an object file
recomp-ui/src/common/sha1.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/sha1.c.o
.PHONY : recomp-ui/src/common/sha1.c.o

recomp-ui/src/common/sha1.i: recomp-ui/src/common/sha1.c.i
.PHONY : recomp-ui/src/common/sha1.i

# target to preprocess a source file
recomp-ui/src/common/sha1.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/sha1.c.i
.PHONY : recomp-ui/src/common/sha1.c.i

recomp-ui/src/common/sha1.s: recomp-ui/src/common/sha1.c.s
.PHONY : recomp-ui/src/common/sha1.s

# target to generate assembly for a file
recomp-ui/src/common/sha1.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/sha1.c.s
.PHONY : recomp-ui/src/common/sha1.c.s

recomp-ui/src/common/sha256.o: recomp-ui/src/common/sha256.c.o
.PHONY : recomp-ui/src/common/sha256.o

# target to build an object file
recomp-ui/src/common/sha256.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/sha256.c.o
.PHONY : recomp-ui/src/common/sha256.c.o

recomp-ui/src/common/sha256.i: recomp-ui/src/common/sha256.c.i
.PHONY : recomp-ui/src/common/sha256.i

# target to preprocess a source file
recomp-ui/src/common/sha256.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/sha256.c.i
.PHONY : recomp-ui/src/common/sha256.c.i

recomp-ui/src/common/sha256.s: recomp-ui/src/common/sha256.c.s
.PHONY : recomp-ui/src/common/sha256.s

# target to generate assembly for a file
recomp-ui/src/common/sha256.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/common/sha256.c.s
.PHONY : recomp-ui/src/common/sha256.c.s

recomp-ui/src/consoles/gb/gb_binds.o: recomp-ui/src/consoles/gb/gb_binds.c.o
.PHONY : recomp-ui/src/consoles/gb/gb_binds.o

# target to build an object file
recomp-ui/src/consoles/gb/gb_binds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/gb/gb_binds.c.o
.PHONY : recomp-ui/src/consoles/gb/gb_binds.c.o

recomp-ui/src/consoles/gb/gb_binds.i: recomp-ui/src/consoles/gb/gb_binds.c.i
.PHONY : recomp-ui/src/consoles/gb/gb_binds.i

# target to preprocess a source file
recomp-ui/src/consoles/gb/gb_binds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/gb/gb_binds.c.i
.PHONY : recomp-ui/src/consoles/gb/gb_binds.c.i

recomp-ui/src/consoles/gb/gb_binds.s: recomp-ui/src/consoles/gb/gb_binds.c.s
.PHONY : recomp-ui/src/consoles/gb/gb_binds.s

# target to generate assembly for a file
recomp-ui/src/consoles/gb/gb_binds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/gb/gb_binds.c.s
.PHONY : recomp-ui/src/consoles/gb/gb_binds.c.s

recomp-ui/src/consoles/genesis/genesis_binds.o: recomp-ui/src/consoles/genesis/genesis_binds.c.o
.PHONY : recomp-ui/src/consoles/genesis/genesis_binds.o

# target to build an object file
recomp-ui/src/consoles/genesis/genesis_binds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/genesis/genesis_binds.c.o
.PHONY : recomp-ui/src/consoles/genesis/genesis_binds.c.o

recomp-ui/src/consoles/genesis/genesis_binds.i: recomp-ui/src/consoles/genesis/genesis_binds.c.i
.PHONY : recomp-ui/src/consoles/genesis/genesis_binds.i

# target to preprocess a source file
recomp-ui/src/consoles/genesis/genesis_binds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/genesis/genesis_binds.c.i
.PHONY : recomp-ui/src/consoles/genesis/genesis_binds.c.i

recomp-ui/src/consoles/genesis/genesis_binds.s: recomp-ui/src/consoles/genesis/genesis_binds.c.s
.PHONY : recomp-ui/src/consoles/genesis/genesis_binds.s

# target to generate assembly for a file
recomp-ui/src/consoles/genesis/genesis_binds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/genesis/genesis_binds.c.s
.PHONY : recomp-ui/src/consoles/genesis/genesis_binds.c.s

recomp-ui/src/consoles/n64/n64_binds.o: recomp-ui/src/consoles/n64/n64_binds.c.o
.PHONY : recomp-ui/src/consoles/n64/n64_binds.o

# target to build an object file
recomp-ui/src/consoles/n64/n64_binds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/n64/n64_binds.c.o
.PHONY : recomp-ui/src/consoles/n64/n64_binds.c.o

recomp-ui/src/consoles/n64/n64_binds.i: recomp-ui/src/consoles/n64/n64_binds.c.i
.PHONY : recomp-ui/src/consoles/n64/n64_binds.i

# target to preprocess a source file
recomp-ui/src/consoles/n64/n64_binds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/n64/n64_binds.c.i
.PHONY : recomp-ui/src/consoles/n64/n64_binds.c.i

recomp-ui/src/consoles/n64/n64_binds.s: recomp-ui/src/consoles/n64/n64_binds.c.s
.PHONY : recomp-ui/src/consoles/n64/n64_binds.s

# target to generate assembly for a file
recomp-ui/src/consoles/n64/n64_binds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/n64/n64_binds.c.s
.PHONY : recomp-ui/src/consoles/n64/n64_binds.c.s

recomp-ui/src/consoles/nes/nes_binds.o: recomp-ui/src/consoles/nes/nes_binds.c.o
.PHONY : recomp-ui/src/consoles/nes/nes_binds.o

# target to build an object file
recomp-ui/src/consoles/nes/nes_binds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/nes/nes_binds.c.o
.PHONY : recomp-ui/src/consoles/nes/nes_binds.c.o

recomp-ui/src/consoles/nes/nes_binds.i: recomp-ui/src/consoles/nes/nes_binds.c.i
.PHONY : recomp-ui/src/consoles/nes/nes_binds.i

# target to preprocess a source file
recomp-ui/src/consoles/nes/nes_binds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/nes/nes_binds.c.i
.PHONY : recomp-ui/src/consoles/nes/nes_binds.c.i

recomp-ui/src/consoles/nes/nes_binds.s: recomp-ui/src/consoles/nes/nes_binds.c.s
.PHONY : recomp-ui/src/consoles/nes/nes_binds.s

# target to generate assembly for a file
recomp-ui/src/consoles/nes/nes_binds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/nes/nes_binds.c.s
.PHONY : recomp-ui/src/consoles/nes/nes_binds.c.s

recomp-ui/src/consoles/psx/memcard_format.o: recomp-ui/src/consoles/psx/memcard_format.c.o
.PHONY : recomp-ui/src/consoles/psx/memcard_format.o

# target to build an object file
recomp-ui/src/consoles/psx/memcard_format.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/psx/memcard_format.c.o
.PHONY : recomp-ui/src/consoles/psx/memcard_format.c.o

recomp-ui/src/consoles/psx/memcard_format.i: recomp-ui/src/consoles/psx/memcard_format.c.i
.PHONY : recomp-ui/src/consoles/psx/memcard_format.i

# target to preprocess a source file
recomp-ui/src/consoles/psx/memcard_format.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/psx/memcard_format.c.i
.PHONY : recomp-ui/src/consoles/psx/memcard_format.c.i

recomp-ui/src/consoles/psx/memcard_format.s: recomp-ui/src/consoles/psx/memcard_format.c.s
.PHONY : recomp-ui/src/consoles/psx/memcard_format.s

# target to generate assembly for a file
recomp-ui/src/consoles/psx/memcard_format.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/psx/memcard_format.c.s
.PHONY : recomp-ui/src/consoles/psx/memcard_format.c.s

recomp-ui/src/consoles/psx/psx_binds.o: recomp-ui/src/consoles/psx/psx_binds.c.o
.PHONY : recomp-ui/src/consoles/psx/psx_binds.o

# target to build an object file
recomp-ui/src/consoles/psx/psx_binds.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/psx/psx_binds.c.o
.PHONY : recomp-ui/src/consoles/psx/psx_binds.c.o

recomp-ui/src/consoles/psx/psx_binds.i: recomp-ui/src/consoles/psx/psx_binds.c.i
.PHONY : recomp-ui/src/consoles/psx/psx_binds.i

# target to preprocess a source file
recomp-ui/src/consoles/psx/psx_binds.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/psx/psx_binds.c.i
.PHONY : recomp-ui/src/consoles/psx/psx_binds.c.i

recomp-ui/src/consoles/psx/psx_binds.s: recomp-ui/src/consoles/psx/psx_binds.c.s
.PHONY : recomp-ui/src/consoles/psx/psx_binds.s

# target to generate assembly for a file
recomp-ui/src/consoles/psx/psx_binds.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/consoles/psx/psx_binds.c.s
.PHONY : recomp-ui/src/consoles/psx/psx_binds.c.s

recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.o: recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.o

recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.i: recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.i

recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.s: recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.cpp.s

recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.o: recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.o

# target to build an object file
recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.o

recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.i: recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.i

# target to preprocess a source file
recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.i

recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.s: recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.s

# target to generate assembly for a file
recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.cpp.s

recomp-ui/src/third_party/imgui/imgui.o: recomp-ui/src/third_party/imgui/imgui.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/imgui.o

# target to build an object file
recomp-ui/src/third_party/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/imgui.cpp.o

recomp-ui/src/third_party/imgui/imgui.i: recomp-ui/src/third_party/imgui/imgui.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/imgui.i

# target to preprocess a source file
recomp-ui/src/third_party/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/imgui.cpp.i

recomp-ui/src/third_party/imgui/imgui.s: recomp-ui/src/third_party/imgui/imgui.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/imgui.s

# target to generate assembly for a file
recomp-ui/src/third_party/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/imgui.cpp.s

recomp-ui/src/third_party/imgui/imgui_draw.o: recomp-ui/src/third_party/imgui/imgui_draw.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/imgui_draw.o

# target to build an object file
recomp-ui/src/third_party/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_draw.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/imgui_draw.cpp.o

recomp-ui/src/third_party/imgui/imgui_draw.i: recomp-ui/src/third_party/imgui/imgui_draw.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/imgui_draw.i

# target to preprocess a source file
recomp-ui/src/third_party/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_draw.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/imgui_draw.cpp.i

recomp-ui/src/third_party/imgui/imgui_draw.s: recomp-ui/src/third_party/imgui/imgui_draw.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/imgui_draw.s

# target to generate assembly for a file
recomp-ui/src/third_party/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_draw.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/imgui_draw.cpp.s

recomp-ui/src/third_party/imgui/imgui_tables.o: recomp-ui/src/third_party/imgui/imgui_tables.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/imgui_tables.o

# target to build an object file
recomp-ui/src/third_party/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_tables.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/imgui_tables.cpp.o

recomp-ui/src/third_party/imgui/imgui_tables.i: recomp-ui/src/third_party/imgui/imgui_tables.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/imgui_tables.i

# target to preprocess a source file
recomp-ui/src/third_party/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_tables.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/imgui_tables.cpp.i

recomp-ui/src/third_party/imgui/imgui_tables.s: recomp-ui/src/third_party/imgui/imgui_tables.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/imgui_tables.s

# target to generate assembly for a file
recomp-ui/src/third_party/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_tables.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/imgui_tables.cpp.s

recomp-ui/src/third_party/imgui/imgui_widgets.o: recomp-ui/src/third_party/imgui/imgui_widgets.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/imgui_widgets.o

# target to build an object file
recomp-ui/src/third_party/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_widgets.cpp.o
.PHONY : recomp-ui/src/third_party/imgui/imgui_widgets.cpp.o

recomp-ui/src/third_party/imgui/imgui_widgets.i: recomp-ui/src/third_party/imgui/imgui_widgets.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/imgui_widgets.i

# target to preprocess a source file
recomp-ui/src/third_party/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_widgets.cpp.i
.PHONY : recomp-ui/src/third_party/imgui/imgui_widgets.cpp.i

recomp-ui/src/third_party/imgui/imgui_widgets.s: recomp-ui/src/third_party/imgui/imgui_widgets.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/imgui_widgets.s

# target to generate assembly for a file
recomp-ui/src/third_party/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/imgui/imgui_widgets.cpp.s
.PHONY : recomp-ui/src/third_party/imgui/imgui_widgets.cpp.s

recomp-ui/src/third_party/tinyfiledialogs.o: recomp-ui/src/third_party/tinyfiledialogs.c.o
.PHONY : recomp-ui/src/third_party/tinyfiledialogs.o

# target to build an object file
recomp-ui/src/third_party/tinyfiledialogs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/tinyfiledialogs.c.o
.PHONY : recomp-ui/src/third_party/tinyfiledialogs.c.o

recomp-ui/src/third_party/tinyfiledialogs.i: recomp-ui/src/third_party/tinyfiledialogs.c.i
.PHONY : recomp-ui/src/third_party/tinyfiledialogs.i

# target to preprocess a source file
recomp-ui/src/third_party/tinyfiledialogs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/tinyfiledialogs.c.i
.PHONY : recomp-ui/src/third_party/tinyfiledialogs.c.i

recomp-ui/src/third_party/tinyfiledialogs.s: recomp-ui/src/third_party/tinyfiledialogs.c.s
.PHONY : recomp-ui/src/third_party/tinyfiledialogs.s

# target to generate assembly for a file
recomp-ui/src/third_party/tinyfiledialogs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/recomp-ui/src/third_party/tinyfiledialogs.c.s
.PHONY : recomp-ui/src/third_party/tinyfiledialogs.c.s

src/codegen_setup.o: src/codegen_setup.c.o
.PHONY : src/codegen_setup.o

# target to build an object file
src/codegen_setup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/src/codegen_setup.c.o
.PHONY : src/codegen_setup.c.o

src/codegen_setup.i: src/codegen_setup.c.i
.PHONY : src/codegen_setup.i

# target to preprocess a source file
src/codegen_setup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/src/codegen_setup.c.i
.PHONY : src/codegen_setup.c.i

src/codegen_setup.s: src/codegen_setup.c.s
.PHONY : src/codegen_setup.s

# target to generate assembly for a file
src/codegen_setup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/src/codegen_setup.c.s
.PHONY : src/codegen_setup.c.s

src/game_launcher_boot.o: src/game_launcher_boot.cpp.o
.PHONY : src/game_launcher_boot.o

# target to build an object file
src/game_launcher_boot.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/src/game_launcher_boot.cpp.o
.PHONY : src/game_launcher_boot.cpp.o

src/game_launcher_boot.i: src/game_launcher_boot.cpp.i
.PHONY : src/game_launcher_boot.i

# target to preprocess a source file
src/game_launcher_boot.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/src/game_launcher_boot.cpp.i
.PHONY : src/game_launcher_boot.cpp.i

src/game_launcher_boot.s: src/game_launcher_boot.cpp.s
.PHONY : src/game_launcher_boot.s

# target to generate assembly for a file
src/game_launcher_boot.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_launcher_ui.dir/build.make CMakeFiles/game_launcher_ui.dir/src/game_launcher_boot.cpp.s
.PHONY : src/game_launcher_boot.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mods/emerald_absolute_rtc_plugin.o: src/mods/emerald_absolute_rtc_plugin.cpp.o
.PHONY : src/mods/emerald_absolute_rtc_plugin.o

# target to build an object file
src/mods/emerald_absolute_rtc_plugin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/mods/emerald_absolute_rtc_plugin.cpp.o
.PHONY : src/mods/emerald_absolute_rtc_plugin.cpp.o

src/mods/emerald_absolute_rtc_plugin.i: src/mods/emerald_absolute_rtc_plugin.cpp.i
.PHONY : src/mods/emerald_absolute_rtc_plugin.i

# target to preprocess a source file
src/mods/emerald_absolute_rtc_plugin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/mods/emerald_absolute_rtc_plugin.cpp.i
.PHONY : src/mods/emerald_absolute_rtc_plugin.cpp.i

src/mods/emerald_absolute_rtc_plugin.s: src/mods/emerald_absolute_rtc_plugin.cpp.s
.PHONY : src/mods/emerald_absolute_rtc_plugin.s

# target to generate assembly for a file
src/mods/emerald_absolute_rtc_plugin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/mods/emerald_absolute_rtc_plugin.cpp.s
.PHONY : src/mods/emerald_absolute_rtc_plugin.cpp.s

src/setup_stubs/cart_dispatch_stub.o: src/setup_stubs/cart_dispatch_stub.cpp.o
.PHONY : src/setup_stubs/cart_dispatch_stub.o

# target to build an object file
src/setup_stubs/cart_dispatch_stub.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/setup_stubs/cart_dispatch_stub.cpp.o
.PHONY : src/setup_stubs/cart_dispatch_stub.cpp.o

src/setup_stubs/cart_dispatch_stub.i: src/setup_stubs/cart_dispatch_stub.cpp.i
.PHONY : src/setup_stubs/cart_dispatch_stub.i

# target to preprocess a source file
src/setup_stubs/cart_dispatch_stub.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/setup_stubs/cart_dispatch_stub.cpp.i
.PHONY : src/setup_stubs/cart_dispatch_stub.cpp.i

src/setup_stubs/cart_dispatch_stub.s: src/setup_stubs/cart_dispatch_stub.cpp.s
.PHONY : src/setup_stubs/cart_dispatch_stub.s

# target to generate assembly for a file
src/setup_stubs/cart_dispatch_stub.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/EmeraldRecomp.dir/build.make CMakeFiles/EmeraldRecomp.dir/src/setup_stubs/cart_dispatch_stub.cpp.s
.PHONY : src/setup_stubs/cart_dispatch_stub.cpp.s

tools/verify_rom_hash/main.o: tools/verify_rom_hash/main.cpp.o
.PHONY : tools/verify_rom_hash/main.o

# target to build an object file
tools/verify_rom_hash/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_rom_hash.dir/build.make CMakeFiles/verify_rom_hash.dir/tools/verify_rom_hash/main.cpp.o
.PHONY : tools/verify_rom_hash/main.cpp.o

tools/verify_rom_hash/main.i: tools/verify_rom_hash/main.cpp.i
.PHONY : tools/verify_rom_hash/main.i

# target to preprocess a source file
tools/verify_rom_hash/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_rom_hash.dir/build.make CMakeFiles/verify_rom_hash.dir/tools/verify_rom_hash/main.cpp.i
.PHONY : tools/verify_rom_hash/main.cpp.i

tools/verify_rom_hash/main.s: tools/verify_rom_hash/main.cpp.s
.PHONY : tools/verify_rom_hash/main.s

# target to generate assembly for a file
tools/verify_rom_hash/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/verify_rom_hash.dir/build.make CMakeFiles/verify_rom_hash.dir/tools/verify_rom_hash/main.cpp.s
.PHONY : tools/verify_rom_hash/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... EmeraldRecomp"
	@echo "... armv4t_tests"
	@echo "... audio_drc_tests"
	@echo "... bios_smoke"
	@echo "... bus_tests"
	@echo "... codegen_shards_tests"
	@echo "... codegen_tests"
	@echo "... decoder_smoke"
	@echo "... dma_tests"
	@echo "... function_finder_tests"
	@echo "... game_launcher_ui"
	@echo "... gba_recompile"
	@echo "... gba_scan"
	@echo "... gbarecomp_armv4t"
	@echo "... gbarecomp_debug"
	@echo "... gbarecomp_gba"
	@echo "... gbarecomp_heal_gate"
	@echo "... gbarecomp_netplay"
	@echo "... gbarecomp_recompile_core"
	@echo "... gbarecomp_runtime"
	@echo "... gen_codegen_tests"
	@echo "... gpio_tests"
	@echo "... heal_gate_tests"
	@echo "... interpreter_smoke"
	@echo "... irq_tests"
	@echo "... link_tests"
	@echo "... mod_runtime_tests"
	@echo "... netplay_smoke_tests"
	@echo "... ppu_smoke_tests"
	@echo "... presentation_layout_tests"
	@echo "... recomp_net"
	@echo "... rtc_tests"
	@echo "... save_config_tests"
	@echo "... selfheal_cluster_test"
	@echo "... symbol_import"
	@echo "... thumb_tests"
	@echo "... timer_tests"
	@echo "... verify_rom_hash"
	@echo "... gbarecomp/host/gbarecomp_codegen_host.o"
	@echo "... gbarecomp/host/gbarecomp_codegen_host.i"
	@echo "... gbarecomp/host/gbarecomp_codegen_host.s"
	@echo "... recomp-ui/src/common/backends/imgui/launcher_imgui.o"
	@echo "... recomp-ui/src/common/backends/imgui/launcher_imgui.i"
	@echo "... recomp-ui/src/common/backends/imgui/launcher_imgui.s"
	@echo "... recomp-ui/src/common/backends/imgui/runtime_ui_imgui.o"
	@echo "... recomp-ui/src/common/backends/imgui/runtime_ui_imgui.i"
	@echo "... recomp-ui/src/common/backends/imgui/runtime_ui_imgui.s"
	@echo "... recomp-ui/src/common/crc32.o"
	@echo "... recomp-ui/src/common/crc32.i"
	@echo "... recomp-ui/src/common/crc32.s"
	@echo "... recomp-ui/src/common/ips_patch.o"
	@echo "... recomp-ui/src/common/ips_patch.i"
	@echo "... recomp-ui/src/common/ips_patch.s"
	@echo "... recomp-ui/src/common/keybinds.o"
	@echo "... recomp-ui/src/common/keybinds.i"
	@echo "... recomp-ui/src/common/keybinds.s"
	@echo "... recomp-ui/src/common/launcher_binds.o"
	@echo "... recomp-ui/src/common/launcher_binds.i"
	@echo "... recomp-ui/src/common/launcher_binds.s"
	@echo "... recomp-ui/src/common/launcher_boot_timing.o"
	@echo "... recomp-ui/src/common/launcher_boot_timing.i"
	@echo "... recomp-ui/src/common/launcher_boot_timing.s"
	@echo "... recomp-ui/src/common/launcher_debug.o"
	@echo "... recomp-ui/src/common/launcher_debug.i"
	@echo "... recomp-ui/src/common/launcher_debug.s"
	@echo "... recomp-ui/src/common/launcher_files.o"
	@echo "... recomp-ui/src/common/launcher_files.i"
	@echo "... recomp-ui/src/common/launcher_files.s"
	@echo "... recomp-ui/src/common/launcher_gl.o"
	@echo "... recomp-ui/src/common/launcher_gl.i"
	@echo "... recomp-ui/src/common/launcher_gl.s"
	@echo "... recomp-ui/src/common/launcher_input.o"
	@echo "... recomp-ui/src/common/launcher_input.i"
	@echo "... recomp-ui/src/common/launcher_input.s"
	@echo "... recomp-ui/src/common/launcher_model.o"
	@echo "... recomp-ui/src/common/launcher_model.i"
	@echo "... recomp-ui/src/common/launcher_model.s"
	@echo "... recomp-ui/src/common/launcher_ng_capi.o"
	@echo "... recomp-ui/src/common/launcher_ng_capi.i"
	@echo "... recomp-ui/src/common/launcher_ng_capi.s"
	@echo "... recomp-ui/src/common/launcher_platform_sdl2.o"
	@echo "... recomp-ui/src/common/launcher_platform_sdl2.i"
	@echo "... recomp-ui/src/common/launcher_platform_sdl2.s"
	@echo "... recomp-ui/src/common/launcher_udp_port.o"
	@echo "... recomp-ui/src/common/launcher_udp_port.i"
	@echo "... recomp-ui/src/common/launcher_udp_port.s"
	@echo "... recomp-ui/src/common/recomp_runtime_settings.o"
	@echo "... recomp-ui/src/common/recomp_runtime_settings.i"
	@echo "... recomp-ui/src/common/recomp_runtime_settings.s"
	@echo "... recomp-ui/src/common/recomp_runtime_ui.o"
	@echo "... recomp-ui/src/common/recomp_runtime_ui.i"
	@echo "... recomp-ui/src/common/recomp_runtime_ui.s"
	@echo "... recomp-ui/src/common/sha1.o"
	@echo "... recomp-ui/src/common/sha1.i"
	@echo "... recomp-ui/src/common/sha1.s"
	@echo "... recomp-ui/src/common/sha256.o"
	@echo "... recomp-ui/src/common/sha256.i"
	@echo "... recomp-ui/src/common/sha256.s"
	@echo "... recomp-ui/src/consoles/gb/gb_binds.o"
	@echo "... recomp-ui/src/consoles/gb/gb_binds.i"
	@echo "... recomp-ui/src/consoles/gb/gb_binds.s"
	@echo "... recomp-ui/src/consoles/genesis/genesis_binds.o"
	@echo "... recomp-ui/src/consoles/genesis/genesis_binds.i"
	@echo "... recomp-ui/src/consoles/genesis/genesis_binds.s"
	@echo "... recomp-ui/src/consoles/n64/n64_binds.o"
	@echo "... recomp-ui/src/consoles/n64/n64_binds.i"
	@echo "... recomp-ui/src/consoles/n64/n64_binds.s"
	@echo "... recomp-ui/src/consoles/nes/nes_binds.o"
	@echo "... recomp-ui/src/consoles/nes/nes_binds.i"
	@echo "... recomp-ui/src/consoles/nes/nes_binds.s"
	@echo "... recomp-ui/src/consoles/psx/memcard_format.o"
	@echo "... recomp-ui/src/consoles/psx/memcard_format.i"
	@echo "... recomp-ui/src/consoles/psx/memcard_format.s"
	@echo "... recomp-ui/src/consoles/psx/psx_binds.o"
	@echo "... recomp-ui/src/consoles/psx/psx_binds.i"
	@echo "... recomp-ui/src/consoles/psx/psx_binds.s"
	@echo "... recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.o"
	@echo "... recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.i"
	@echo "... recomp-ui/src/third_party/imgui/backends/imgui_impl_opengl3.s"
	@echo "... recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.o"
	@echo "... recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.i"
	@echo "... recomp-ui/src/third_party/imgui/backends/imgui_impl_sdl2.s"
	@echo "... recomp-ui/src/third_party/imgui/imgui.o"
	@echo "... recomp-ui/src/third_party/imgui/imgui.i"
	@echo "... recomp-ui/src/third_party/imgui/imgui.s"
	@echo "... recomp-ui/src/third_party/imgui/imgui_draw.o"
	@echo "... recomp-ui/src/third_party/imgui/imgui_draw.i"
	@echo "... recomp-ui/src/third_party/imgui/imgui_draw.s"
	@echo "... recomp-ui/src/third_party/imgui/imgui_tables.o"
	@echo "... recomp-ui/src/third_party/imgui/imgui_tables.i"
	@echo "... recomp-ui/src/third_party/imgui/imgui_tables.s"
	@echo "... recomp-ui/src/third_party/imgui/imgui_widgets.o"
	@echo "... recomp-ui/src/third_party/imgui/imgui_widgets.i"
	@echo "... recomp-ui/src/third_party/imgui/imgui_widgets.s"
	@echo "... recomp-ui/src/third_party/tinyfiledialogs.o"
	@echo "... recomp-ui/src/third_party/tinyfiledialogs.i"
	@echo "... recomp-ui/src/third_party/tinyfiledialogs.s"
	@echo "... src/codegen_setup.o"
	@echo "... src/codegen_setup.i"
	@echo "... src/codegen_setup.s"
	@echo "... src/game_launcher_boot.o"
	@echo "... src/game_launcher_boot.i"
	@echo "... src/game_launcher_boot.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mods/emerald_absolute_rtc_plugin.o"
	@echo "... src/mods/emerald_absolute_rtc_plugin.i"
	@echo "... src/mods/emerald_absolute_rtc_plugin.s"
	@echo "... src/setup_stubs/cart_dispatch_stub.o"
	@echo "... src/setup_stubs/cart_dispatch_stub.i"
	@echo "... src/setup_stubs/cart_dispatch_stub.s"
	@echo "... tools/verify_rom_hash/main.o"
	@echo "... tools/verify_rom_hash/main.i"
	@echo "... tools/verify_rom_hash/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

