# CMake generated Testfile for 
# Source directory: /home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp
# Build directory: /home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("mod_runtime_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/mod_runtime_tests")
set_tests_properties("mod_runtime_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;571;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("runtime_monolith_guard" "/usr/bin/cmake" "-DGBARECOMP_RUNTIME_CMAKE=/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/runtime.cmake" "-DGBARECOMP_TEST_SOURCE=/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/tests/cmake/runtime_monolith_guard" "-DGBARECOMP_TEST_BINARY=/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/runtime_monolith_guard_test" "-DGBARECOMP_TEST_GENERATOR=Unix Makefiles" "-P" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/tests/cmake/assert_runtime_monolith_guard.cmake")
set_tests_properties("runtime_monolith_guard" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;574;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("decoder_smoke" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/decoder_smoke")
set_tests_properties("decoder_smoke" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;584;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("function_finder_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/function_finder_tests")
set_tests_properties("function_finder_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;588;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("codegen_shards_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/codegen_shards_tests")
set_tests_properties("codegen_shards_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;592;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("audio_drc_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/audio_drc_tests")
set_tests_properties("audio_drc_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;596;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("selfheal_cluster_test" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/selfheal_cluster_test")
set_tests_properties("selfheal_cluster_test" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;604;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("interpreter_smoke" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/interpreter_smoke")
set_tests_properties("interpreter_smoke" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;608;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("armv4t_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/armv4t_tests")
set_tests_properties("armv4t_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;612;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("thumb_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/thumb_tests")
set_tests_properties("thumb_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;616;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("bus_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/bus_tests")
set_tests_properties("bus_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;416;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;618;add_gbarecomp_runtime_stack_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("dma_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/dma_tests")
set_tests_properties("dma_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;416;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;619;add_gbarecomp_runtime_stack_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("timer_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/timer_tests")
set_tests_properties("timer_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;623;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("gpio_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/gpio_tests")
set_tests_properties("gpio_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;627;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("link_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/link_tests")
set_tests_properties("link_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;633;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("netplay_smoke_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/netplay_smoke_tests")
set_tests_properties("netplay_smoke_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;643;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("rtc_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/rtc_tests")
set_tests_properties("rtc_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;648;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("irq_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/irq_tests")
set_tests_properties("irq_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;652;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("ppu_smoke_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/ppu_smoke_tests")
set_tests_properties("ppu_smoke_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;662;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("save_config_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/save_config_tests")
set_tests_properties("save_config_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;669;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("presentation_layout_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/presentation_layout_tests")
set_tests_properties("presentation_layout_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;673;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("heal_gate_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/heal_gate_tests")
set_tests_properties("heal_gate_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;680;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
add_test("codegen_tests" "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp_build/codegen_tests")
set_tests_properties("codegen_tests" PROPERTIES  _BACKTRACE_TRIPLES "/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;740;add_test;/home/alex/Documents/GitHub/EmeraldRecomp/gbarecomp/CMakeLists.txt;0;")
subdirs("../recomp-net-build")
